### ISSUE TITLE
Why is OnCreateView Sample @Nullable

### ISSUE THREAD

**Issue by MSIH** [Appolica/InteractiveInfoWindowAndroid#10]
Is it necessary to use @Nullable on the OnCreateView, as you did in your sample?

**Comment by deangenovski** [comment]
No, @Nullable is just there to point out that this argument can be null, so you should perform null check before using it. The support library also has this annotation. It doesn't affect the actual code execution at all. You can omit it if you want to.

I will close the issue.

If you like our work, please give us a star :)
