### ISSUE TITLE
How to hide info window after View.OnClickListener

### ISSUE THREAD

**Issue by MSIH** [Appolica/InteractiveInfoWindowAndroid#11]
From within the fragment, I have defined an View.OnClickListener. What code do I use to close the infowindow. How do I call this "public void hide(@NonNull final InfoWindow infoWindow, final boolean animated) - Hides the given InfoWindow with or without animation." from within the fragment?

**Comment by deangenovski** [comment]
If you are using the infoWindowManager in your activity, you can call getActivity() in your fragment and cast to your particular activity and get the infoWindowManager from the activity.

There is nothing magic in this library so every example out there that shows communication between fragment -> activity or fragment -> fragment is valid.

**Comment by MSIH** [comment]
Once I have the infoWindowManager, how do I get the infoWindow to pass to the hide method?

**Comment by MSIH** [comment]
Do you have a few minutes to incorporate hiding the infowondow in your example? I am at a loss of how to get the infowindow to pass to the 


public void onClick(View v) {
                Toast.makeText(getContext(), "Well I don't have any...", Toast.LENGTH_SHORT).show();

final MapInfoWindowFragment mapInfoWindowFragment =
        (MapInfoWindowFragment) getSupportFragmentManager().findFragmentById(R.id.infoWindowMap);

  final InfoWindow infoWindow = ??

  // hides it if it is already opened.
  mapInfoWindowFragment.infoWindowManager().hide(infoWindow, true); 
            }
```
```
