### ISSUE TITLE
Where can i put the API Key in Sample Project?

### ISSUE THREAD

**Issue by guitar9** [Appolica/InteractiveInfoWindowAndroid#19]
Hello,
where can i put the Google Maps API Key in the sample Project? There is no "google_maps_api.xml"

**Comment by pingpingsim** [comment]
It's inside sample folder's manifest file. https://github.com/Appolica/InteractiveInfoWindowAndroid/blob/master/InteractiveInfoWindowAndroid/sample/src/main/AndroidManifest.xml

**Comment by deangenovski** [comment]
@pingpingsim is correct
