### ISSUE TITLE
How to remove background white color from info window ?

### ISSUE THREAD

**Issue by dhar619** [Appolica/InteractiveInfoWindowAndroid#2]
Thanks for the library mate. I want to remove the white background and make it transparent with two buttons when I click on map marker. Is there any way to do it ?
Please guide me through it.

**Comment by bkolarov-appolica** [comment]
It seems that I haven't implemented that feature. At least not completely.. Stay tuned, an update is coming soon.

**Comment by rizasif** [comment]
Transparent window feature is implemented here:
https://github.com/rizasif/InteractiveInfoWindowAndroid

A pull request is also created:
https://github.com/Appolica/InteractiveInfoWindowAndroid/pull/4

**Comment by deangenovski** [comment]
A custom background feature has already been implemented and is pushed to develop. We will update the documentation and upload the gradle dependency shortly.

**Comment by deangenovski** [comment]
You could check out develop branch and look at InfoWindowManager.ContainerSpecification.

**Comment by dhar619** [comment]
@rizasif sure mate, will check and let you know. Thank you.

**Comment by dhar619** [comment]
@deangenovski yes, I have removed the drawable from nfoWindowManager.ContainerSpecification ;)

**Comment by bkolarov-appolica** [comment]
The new release is out! I updated the README.md. You can now easily set your own background drawable. Sorry it took so long. Enjoy :)
