### ISSUE TITLE
Scrollcontainer inside the info window && hideOnFling

### ISSUE THREAD

**Issue by maxim-petlyuk** [Appolica/InteractiveInfoWindowAndroid#21]
When we have the scroll container inside the info window view, then the callback of the GestureDetector.onFling will hide the info window after the attempt to scroll content inside the info window view.

**Comment by deangenovski** [comment]
We are aware of the problem.

@bkolarov-appolica Was the version with the fix for the above problem released ? Or is it just merged in develop ?

**Comment by deangenovski** [comment]
It looks like it hasn't been released, yet. Will release it as soon as we can. Meanwhile you can check the develop branch, it should be ok there.

**Comment by maxim-petlyuk** [comment]
Thanks for the quick answer.
I research the develop branch and seems to me there is no fix there. If I am not wrong, GestureDetector.onFling should check if the action_down event inside the info window container - then callback should return false.

**Comment by deangenovski** [comment]
[DisallowInterceptLayout](https://github.com/Appolica/InteractiveInfoWindowAndroid/blob/develop/InteractiveInfoWindowAndroid/interactive-info-window/src/main/java/com/appolica/interactiveinfowindow/customview/DisallowInterceptLayout.java) - Every info window is wrapped with that layout. It prevents the parent from intercepting the touch events that are inside the info window.

**Comment by maxim-petlyuk** [comment]
Great and clear job! Thank you for your time and help! Nice and helpful solution.

**Comment by deangenovski** [comment]
We will let you know as soon as we release the new version, so that you can use the gradle dependency directly :)

If you like our work, please give us a star :)

**Comment by maxim-petlyuk** [comment]
> If you like our work, please give us a star :)

Sure :) Already done :)

**Comment by rokn** [comment]
The fix is released now
