### ISSUE TITLE
The project is not built due to values-24.xml

### ISSUE THREAD

**Issue by arvalon** [Appolica/InteractiveInfoWindowAndroid#22]
The project is not built due to values-24.xml
Added to the project dependency
`compile 'com.appolica:interactive-info-window:v1.0.6'`
When you build get errors in the file values-24.xml:

> C:\Users\***\app\build\intermediates\res\merged\debug\values-v24\values-v24.xml
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

The text file values-24.xml:

`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="Base.TextAppearance.AppCompat.Widget.Button.Borderless.Colored" parent="android:TextAppearance.Material.Widget.Button.Borderless.Colored"/>
    <style name="Base.TextAppearance.AppCompat.Widget.Button.Colored" parent="android:TextAppearance.Material.Widget.Button.Colored"/>
    <style name="TextAppearance.AppCompat.Notification.Info.Media"/>
    <style name="TextAppearance.AppCompat.Notification.Media"/>
    <style name="TextAppearance.AppCompat.Notification.Time.Media"/>
    <style name="TextAppearance.AppCompat.Notification.Title.Media"/>
</resources>`

build.gradle app module:

`apply plugin: 'com.android.application'

android {
compileSdkVersion 23
buildToolsVersion '25.0.2'
defaultConfig {
applicationId "***"
minSdkVersion 16
targetSdkVersion 23
versionCode 1
versionName "1.0"
multiDexEnabled true
}
buildTypes {
release {
minifyEnabled false
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
}
}
repositories {
jcenter()
maven { url 'http://repo1.maven.org/maven2' }
maven { url 'http://dl.bintray.com/journeyapps/maven' }
}
}
android {
buildToolsVersion '25.0.2'
compileSdkVersion 23
useLibrary 'org.apache.http.legacy'
}
dependencies {
compile fileTree(include: ['*.jar'], dir: 'libs')
androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
exclude group: 'com.android.support', module: 'support-annotations'
})
compile files('libs/picasso-2.5.2.jar')

compile 'com.android.support:multidex:1.0.1'
compile 'com.android.support:appcompat-v7:23.4.0'
compile 'com.android.support:support-v4:23.4.0'
compile 'com.android.support:cardview-v7:23.4.0'
compile 'com.android.support:design:23.4.0'
compile 'com.android.support:recyclerview-v7:23.4.0'
compile 'com.google.android.gms:play-services:8.4.0'
compile 'com.google.android.gms:play-services-maps:8.4.0'

compile 'com.journeyapps:zxing-android-embedded:3.4.0'
compile 'io.github.luizgrp.sectionedrecyclerviewadapter:sectionedrecyclerviewadapter:1.0.4'
compile 'de.hdodenhof:circleimageview:2.1.0'
compile 'org.florescu.android.rangeseekbar:rangeseekbar-library:0.3.0'
compile 'org.greenrobot:eventbus:3.0.0'
compile 'commons-io:commons-io:20030203.000550'
compile 'com.appolica:interactive-info-window:v1.0.6'
testCompile 'junit:junit:4.12'}`

**Comment by bkolarov-appolica** [comment]
Hi, @Arvalon,
Thank you for using our library. Would you try changing your compileSdkVersion to 25?

**Comment by arvalon** [comment]
Yes, it helped. Thank you

**Comment by bkolarov-appolica** [comment]
Glad we were helpful. Please give us a star if you like our work. Good luck!
