### ISSUE TITLE
InfoWindow comes from right instead of Marker when Layout is RTL

### ISSUE THREAD

**Issue by ZaidMirza** [Appolica/InteractiveInfoWindowAndroid#27]
Hi, 

when Layout is LTR, InfoWindow animates from Marker but When Layout is RTL infoWindow animates from right of screen instead of Marker. I think as Infowindow is a fragment so when Layotu is RTL  animation is not correctly applied.

**Comment by dpetrov-appolica** [comment]
Resolved in the new version.
