### ISSUE TITLE
Incorrect horizontal infowindow background scale

### ISSUE THREAD

**Issue by dmz9** [Appolica/InteractiveInfoWindowAndroid#29]
While running on emulator i noticed that infowindow background is displayed wrong.
![apo](https://user-images.githubusercontent.com/19429896/36370108-e11018ba-156e-11e8-827e-d13411aa0ada.png)
It looks like the arrow has some wrong bias to the left, shifting more if window has larger horizontal size.
I found that this issue is related to 9-patch markup of the png background infowindow_background.9.png
Android studio shows that the background has wrong patches on both sides of horizontal stretching areas.
![apo2](https://user-images.githubusercontent.com/19429896/36370277-8aae8c94-156f-11e8-8713-0129e23c233f.png)
So i tried to fix that by making the stretch area 1px-wide. It did help.
This issue is created for purpose - if somebody like me will get into it - here is the solution:
copy all /res/drawable-***dpi-v4/infowindow_background.9.png in your project's /res/ folder and resize horizontal stretch areas to 1px
![apo3](https://user-images.githubusercontent.com/19429896/36370740-dbd45756-1570-11e8-9c9b-d616c1b1f892.png)

**Comment by deangenovski** [comment]
Would be keen on creating a PR for the fix

**Comment by rapperskull** [comment]
Any news on merging this?

**Comment by deangenovski** [comment]
Merged will be release with 1.0.8
