### ISSUE TITLE
mapinfowindowfragemnt - adding a recycler view and scroll it - window closes on lift finger

### ISSUE THREAD

**Issue by thebeancounter** [Appolica/InteractiveInfoWindowAndroid#33]
Hi 

I am using the awesome map info window fragment, and adding a recycler view to it, when scrolling it works fine, but when I lift the finger, the popup closes. Which is a problem.

Does anyone know about that issue or how to solve it? 

Maybe the map under the pop up "feels" my touch and closes?

Thanks!

**Comment by thebeancounter** [comment]
update: 
When scrolling the recyclerview very slowly and lifting the finger very gently, it does not close.
When performing a "scrolling gesture" on other parts of the popup which are not the recycler view, it also closes the popup.

**Comment by deangenovski** [comment]
Hi,

This sounds related to the `hideOnFling` feature.

> The InfoWindow lags when you fling the map. However if you want to hide it instead of moving it with the map, you can use InfoWindowManager.setHideOnFling(final boolean hideOnFling). We are open to suggestions how to fix this.

**Comment by deangenovski** [comment]
However I think that we should probably not take that into account when the fling event is within the bounds of your info window. So this seems like a valid issue.

**Comment by deangenovski** [comment]
Seems like the issue was fixed and will be released with 1.0.8 .
