### ISSUE TITLE
how to make transparent background of infowindow?

### ISSUE THREAD

**Issue by osolodkin** [Appolica/InteractiveInfoWindowAndroid#34]
Hello, man! 
Thanks for excellent lib! 
It works perfect!
Please advice how can I make transparent background of InfoWindow instead of white rectangle?
In original Google solution it makes when you set up GoogleMap.InfoWindowAdapter.getInfoWindow instead getInfoContents.
Thanks!

**Comment by deangenovski** [comment]
Hey, you need to look at InfoWindowManager::ContainerSpecification. You can specify a different image to go as a background of the infowindow
