### ISSUE TITLE
How to make communication between ParentFragment and Appolica InfoWindowFragment

### ISSUE THREAD

**Issue by Yuri07** [Appolica/InteractiveInfoWindowAndroid#37]
I tried to use callback to communicate between my fragments but it seems that infowindowfragment does not recognize my mapFragment as its parentfragment, is there something I can do to work or have another way to do this?

Mapfragment(parentFragment):

![image](https://user-images.githubusercontent.com/11671933/41069906-50ee01aa-69c6-11e8-803c-b44674c660d8.png)

![image](https://user-images.githubusercontent.com/11671933/41069959-8a7bf594-69c6-11e8-99d1-16ff410935bc.png)

![image](https://user-images.githubusercontent.com/11671933/41069980-ab6da932-69c6-11e8-8fff-edb861f3e209.png)

![image](https://user-images.githubusercontent.com/11671933/41070013-cfa3d420-69c6-11e8-87a9-a0f0019153b1.png)

![image](https://user-images.githubusercontent.com/11671933/41070183-d30deb9a-69c7-11e8-93c1-4fe7d7377184.png)

InfoWindowFragment:
![image](https://user-images.githubusercontent.com/11671933/41069855-0e7ec3d6-69c6-11e8-84b3-6dfb8e90b981.png)

Logcat:
![image](https://user-images.githubusercontent.com/11671933/41069813-e70bf9ea-69c5-11e8-8002-65ec69d27e20.png)

**Comment by dpetrov-appolica** [comment]
`Fragment fragment = null;
        if (getParentFragment() != null) {
            fragment = getParentFragment().getParentFragment();
            
        }
        if (fragment instanceof OnChildFragmentInteractionListener) {
            listener = (OnChildFragmentInteractionListener) fragment;
        } else {
            throw new RuntimeException("The parent fragment must implement OnChildFragmentInteractionListener");
        }`

The reason your check isn't working is because getParentFragment() returns you the MapInfoWindowFragment.

**Comment by dpetrov-appolica** [comment]
![Screenshot from 2021-06-23 14-31-15](https://user-images.githubusercontent.com/85936147/123089791-158ccd80-d430-11eb-895e-117e0d04b95f.png)

The reason your check isn't working is because getParentFragment() returns you the MapInfoWindowFragment.
getParentFragment().getParentFragment() will return your MapFragment and the your check will be true.
