### ISSUE TITLE
Incorrect x offset

### ISSUE THREAD

**Issue by JinHo95** [Appolica/InteractiveInfoWindowAndroid#38]
The info window does not show exactly on top of marker when there is no map animation. How to fix it?
Ive set the x off set to 0.

**Comment by avisingh736** [comment]
Yes, I have this problem too. Some of devices showing info window at right place but some another devices not.
Not at right place in: Redmi 6 Pro

**Comment by deangenovski** [comment]
Should be fixed by https://github.com/Appolica/InteractiveInfoWindowAndroid/issues/29
