### ISSUE TITLE
Help! Cannot initialize InfoWindow constructors

### ISSUE THREAD

**Issue by Davo77** [Appolica/InteractiveInfoWindowAndroid#39]
Hi!

I get this error when trying to initialize InfoWindow on the MainActivity.
MainActivity is coded on Kotlin.

![error](https://user-images.githubusercontent.com/39403300/41868546-08aba732-78bf-11e8-95a5-2c532f93b41e.png)

Thank you for your help.

**Comment by deangenovski** [comment]
You don't seem to have marker and markerSpec variables in your scope
