### ISSUE TITLE
OnCameraIdleListener not fired

### ISSUE THREAD

**Issue by Innova133** [Appolica/InteractiveInfoWindowAndroid#40]
When setting an OnCameraIdleListener on the googleMap object returned from getMapAsync, the onCameraIdle method is never called.

This also happens for many other interfaces, OnMapClickListener, etc.

This issue seems to only exist in the MapFragmentActivity, not the MapViewActivity.

**Comment by rafaguedes** [comment]
The same for me.
The method OnMapClickListener is not being called.

**Comment by rafaguedes** [comment]
Implement the method from your infoWindowManager() from your MapInfoWindowFragment.
Like this:
mapFragment.infoWindowManager().setOnMapClickListener(onMapClickListener);

**Comment by deangenovski** [comment]
@rafaguedes is correct
