### ISSUE TITLE
JCenter is deprecated

### ISSUE THREAD

**Issue by sryze** [Appolica/InteractiveInfoWindowAndroid#55]
Can you please publish this package in Maven Central? JCenter is being deprecated and will stop working soon:

https://stackoverflow.com/questions/66651640/jcenter-deprecation-impact-on-gradle-and-android

![image](https://user-images.githubusercontent.com/4525736/120069543-48011000-c0a8-11eb-8688-b915dedfae6a.png)

**Comment by sryze** [comment]
BTW the download link in README also gives 404 - https://bintray.com/appolica-ltd/appolica/InfoWindow/_latestVersion

**Comment by dpetrov-appolica** [comment]
The library is migrated to Maven Central.
